require("user.options")
require("user.keymaps")
require("user.plugins")
-- require("user.cmp")
-- require("user.lsp")
require("user.telescope")
require("user.comment")
require("user.gitsigns")
require("user.treesitter")
-- require("user.autopairs")
require("user.nvim-tree")
require("user.bufferline")
require("user.whichkey")
-- require("user.toggleterm")
require("user.lualine")
